name: morpheme_http
description: Future-based library for making HTTP requests modified from http package.
version: 6.1.0
homepage: https://morpheme.design/
repository: https://github.com/morphemedesign/morpheme-flutter-library/tree/main/packages/morpheme_http

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  uuid: ^4.5.1
  equatable: ^2.0.7
  logger: ^2.6.1
  path_provider: ^2.1.5
  flat_buffers: ^23.5.26
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  mime: ^2.0.0
  http_parser: ^4.1.2

  morpheme_inspector: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  objectbox_generator: ^4.3.0

objectbox:
  output_dir: src/cache_strategy/model
