name: morpheme_cucumber
description: A gherkin / cucumber integration test runner flutter with morpheme_cli.
version: 1.1.0
homepage: https://morpheme.design/
repository: https://github.com/morphemedesign/morpheme-flutter-library/tree/main/packages/morpheme_cucumber

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter

  collection: ^1.19.1
  equatable: ^2.0.7
  patrol: ^3.19.0
  patrol_finders: ^2.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
