// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../src/model/cached_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2869433853237476117),
      name: 'CachedModel',
      lastPropertyId: const obx_int.IdUid(4, 4092846322280810695),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7036693601904197759),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1495256193109823312),
            name: 'imageUrl',
            type: 9,
            flags: 32808,
            indexId: const obx_int.IdUid(1, 1062353948333248470)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9160181854140831260),
            name: 'image',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4092846322280810695),
            name: 'ttl',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 2869433853237476117),
      lastIndexId: const obx_int.IdUid(1, 1062353948333248470),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    CachedModel: obx_int.EntityDefinition<CachedModel>(
        model: _entities[0],
        toOneRelations: (CachedModel object) => [],
        toManyRelations: (CachedModel object) => {},
        getId: (CachedModel object) => object.id,
        setId: (CachedModel object, int id) {
          object.id = id;
        },
        objectToFB: (CachedModel object, fb.Builder fbb) {
          final imageUrlOffset = fbb.writeString(object.imageUrl);
          final imageOffset = fbb.writeListInt8(object.image);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, imageUrlOffset);
          fbb.addOffset(2, imageOffset);
          fbb.addInt64(3, object.ttl);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final imageParam = const fb.Uint8ListReader(lazy: false)
              .vTableGet(buffer, rootOffset, 8, Uint8List(0)) as Uint8List;
          final ttlParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = CachedModel(
              imageUrl: imageUrlParam, image: imageParam, ttl: ttlParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CachedModel] entity fields to define ObjectBox queries.
class CachedModel_ {
  /// See [CachedModel.id].
  static final id =
      obx.QueryIntegerProperty<CachedModel>(_entities[0].properties[0]);

  /// See [CachedModel.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<CachedModel>(_entities[0].properties[1]);

  /// See [CachedModel.image].
  static final image =
      obx.QueryByteVectorProperty<CachedModel>(_entities[0].properties[2]);

  /// See [CachedModel.ttl].
  static final ttl =
      obx.QueryIntegerProperty<CachedModel>(_entities[0].properties[3]);
}
